// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmuwhjgqdomvqelvwhrs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtdXdoamdxZG9tdnFlbHZ3aHJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NjU4ODMsImV4cCI6MjA2NzI0MTg4M30.8bKj6vfudSsKjyhl8z3iyR-FZiFVUFWgIGlkV3nzDmU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});